### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe Kafka Test",
  "email": "kafak_test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

### Create a new patient without email
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

### Create a new patient without registeredDate
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}
###